export const ROUTES = {
  HOME: '/',
  LOGIN: '/dang-nhap',
  REGISTER: '/dang-ky',
  FORGOT_PASSWORD: '/quen-mat-khau',
  RESET_PASSWORD: '/dat-lai-mat-khau',
  VERIFY_EMAIL: '/xac-thuc-email',
  PRODUCTS: '/san-pham',
  PRODUCT_DETAIL: '/san-pham/:slug',
  CART: '/gio-hang',
  WISHLIST: '/san-pham-yeu-thich',
  ORDERS: '/don-hang',
  ORDER_DETAIL: '/don-hang/:id',
  PROFILE: '/tai-khoan',
  STORES: '/cua-hang',
  PASS: '/hang-pass',
  PASS_DETAIL: '/hang-pass/:slug',
  NEWS: '/tin-tuc',
  TRAINING: '/dao-tao',
  DEALS: '/giam-gia',
  CAREERS: '/tuyen-dung',
  CONTACT: '/lien-he',
  // Admin Routes
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_BRANDS: '/admin/brands',
  OWNER: '/owner',
  OWNER_DASHBOARD: '/owner/dashboard',
  OWNER_PRODUCTS: '/owner/products',
  OWNER_SHOP: '/owner/shop',
} as const;
